// <auto-generated />
namespace gu_s.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Intial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intial));
        
        string IMigrationMetadata.Id
        {
            get { return "201302202125135_Intial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
